//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaint()
        {
            this.ComplaintsDepartments = new HashSet<ComplaintsDepartment>();
        }
    
        public int ComplaintID { get; set; }
        public int ComplaintStatusID { get; set; }
        public int UserID { get; set; }
        public bool Refund { get; set; }
        public int CountryID { get; set; }
        public string Details { get; set; }
        public int ContactMethod { get; set; }
        public Nullable<System.DateTime> ComplaintLoggedTime { get; set; }
    
        public virtual ComplaintStatu ComplaintStatu { get; set; }
        public virtual ContactMethod ContactMethod1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintsDepartment> ComplaintsDepartments { get; set; }
    }
}
